runtime: python27
api_version: 1
threadsafe: true

error_handlers:
- file: public/404.html

handlers:
- url: /
  secure: always
  static_files: public/index.html
  upload: public/index.html

# For Hugo
- url: /(.*)/
  secure: always
  static_files: public/\1/index.html
  upload: public/(.*)/index.html

- url: /(.*)
  secure: always
  static_files: public/\1
  upload: public/(.*)

# Upload only the ./public directory
skip_files:
- ^(?!^public).*$
