baseURL = 'https://www.cyberfortress.com'
languageCode = 'en-us'
title = 'CyberFortress'
theme = ''

[params]
  description = "Digital means vulnerable. CyberFortress is building a new way to protect your online revenue in minutes."

[taxonomies]
  tag = "tags"

[permalinks]
  team = "/:slug/"
  html = "/:slug/"
  md = "/:slug/"

[blackfriday]
  hrefTargetBlank = true
