# baseURL = 'https://www.cyberfortress.com'
languageCode = 'en-us'
title = 'CyberFortress'
theme = ''

[params]
description = "CyberFortress offers a new kind of insurance for e-commerce! Parametric in nature, we pay out fast on lost revenue due to unexpected downtime."

disableKinds = ["taxonomy", "taxonomyTerm"]

# Disable taxonomies
[taxonomies]

[blackfriday]
  hrefTargetBlank = true
